export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const SAVE_TV_SHOW = 'SAVE_TV_SHOW';
export const SAVE_TV_SHOW_SUCCESS = 'SAVE_TV_SHOW_SUCCESS';

export const LOAD_SHOWS = 'LOAD_SHOWS';
export const LOAD_SHOWS_SUCCESS = 'LOAD_SHOWS_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
