export const SAVE_TV_SHOW = 'SAVE_TV_SHOW';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SAVE_TV_SHOW_SUCCESS = 'SAVE_TV_SHOW_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
